name: Build Configs from Rules

on:
  push:
    branches:
      - main
    paths:
      - 'ProxyRules/MyRules.toml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # latest python
      - name: Checkout Repository to Workspace
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Build Script
        run: |
          echo "Building Start"
          python ProxyRules/update_from_myrules.py
          echo "Building Complete"
