name: Build Configs from Rules

on:
  push:
    branches:
      - main
    paths:
      - 'ProxyRules/MyRules.toml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository to Workspace
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # latest python
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Build Script
        run: python ProxyRules/update_from_myrules.py --no-pause
      - run: |
          git status
      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
